Aplication/Web/Controllers/ProductosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DAL.Data;
using DAL.Models;

namespace Web.Controllers
{
    [Authorize]
    public class ProductosController : Controller
    {
        ProductoRepository productoRepository = new ProductoRepository();
        // GET: Productos
        public ActionResult Index()
        {
            var producto = productoRepository.GetList(null,
                new string[] { typeof(LineaProducto).Name,
                    typeof(SubLineaProducto).Name, typeof(UnidadMedida).Name });

            return View(producto.ToList());
        }


        // GET: Productos/Create
        public ActionResult Create()
        {
            @ViewBag.resultado = TempData["resultado"];
            TempData["resultado"] = null;

            ViewBag.CodLin = new SelectList(new LineaProductoRepository().GetList(null,null),
                "CodLin", "DesLin");
            ViewBag.CodSubLin = new SelectList(new SubLineaProductoRepository().GetList(null,null),
                "CodSubLin", "DesLin");
            ViewBag.CodUniMed = new SelectList(new UnidadMedidaRepository().GetList(null,null), 
                "CodUnidadMed", "DesUniMed");
            return View();
        }

        // POST: Productos/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CodPro,CodLin,CodSubLin,NomPro,estado,CodUniMed,precio,afectoigv,TipPro")] Producto producto)
        {
            if (ModelState.IsValid)
            {
                productoRepository.Insert(producto);
                TempData["resultado"] = "Grabacion satisfactoria";

                return RedirectToAction("Index");
            }

            ViewBag.CodLin = new SelectList(new LineaProductoRepository().GetList(null, null), 
                "CodLin", "DesLin", producto.CodLin);
            ViewBag.CodSubLin = new SelectList(new SubLineaProductoRepository().GetList(null, null),
                "CodSubLin", "DesLin", producto.CodSubLin);
            ViewBag.CodUniMed = new SelectList(new UnidadMedidaRepository().GetList(null, null),
                "CodUnidadMed", "DesUniMed", producto.CodUniMed);
            return View(producto);
        }

        // GET: Productos/Edit/5
        public ActionResult Edit(string id)
        {
            @ViewBag.resultado = TempData["resultado"];
            TempData["resultado"] = null;

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producto producto = productoRepository.GetOne(x => x.CodPro.Equals(id),
                new string[] {typeof(TabFotos).Name });

            if (producto == null)
            {
                return HttpNotFound();
            }
            ViewBag.CodLin = new SelectList(new LineaProductoRepository().GetList(null, null), 
                "CodLin", "DesLin", producto.CodLin);
            ViewBag.CodSubLin = new SelectList(new SubLineaProductoRepository().GetList(null, null),
                "CodSubLin", "DesLin", producto.CodSubLin);
            ViewBag.CodUniMed = new SelectList(new UnidadMedidaRepository().GetList(null, null), 
                "CodUnidadMed", "DesUniMed", producto.CodUniMed);
            return View(producto);
        }

        // POST: Productos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CodPro,CodLin,CodSubLin,NomPro,estado,CodUniMed,precio,afectoigv,TipPro")] Producto producto)
        {
            if (ModelState.IsValid)
            {
                productoRepository.Update(producto);
                TempData["resultado"] = "Grabacion satisfactoria";

                return RedirectToAction("Edit");
            }
            ViewBag.CodLin = new SelectList(new LineaProductoRepository().GetList(null, null),
                "CodLin", "DesLin", producto.CodLin);
            ViewBag.CodSubLin = new SelectList(new SubLineaProductoRepository().GetList(null, null),
                "CodSubLin", "CodLin", producto.CodSubLin);
            ViewBag.CodUniMed = new SelectList(new UnidadMedidaRepository().GetList(null, null),
                "CodUnidadMed", "DesUniMed", producto.CodUniMed);
            return View(producto);
        }

    }
}

Aplication/Web/Controllers/TabFotosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DAL.Data;
using DAL.Models;

namespace Web.Controllers
{
    [Authorize]
    public class TabFotosController : Controller
    {
        TabFotosRepository tabFotosRepository = new TabFotosRepository();

        // GET: TabFotos
        public ActionResult Index()
        {
            var tabFotos =tabFotosRepository.GetList(null,new string[] {typeof(Producto).Name });
            return View(tabFotos.ToList());
        }


        // GET: TabFotos/Create
        public ActionResult Create(String CodPro)
        {

            ViewBag.Codigo = new SelectList(new ProductoRepository().GetList(null, null), "CodPro", "CodPro", CodPro);
            ViewBag.Producto = CodPro;
            return View();
        }

        private string subirFoto(String codProducto, String item)
        {
            var imagePath = "";
            var photoName = codProducto + "_" + item;
            if (Request.Files.Count > 0)
            {
                var file = Request.Files[0];

                if (file != null && file.ContentLength > 0)
                {
                    var extension = Path.GetExtension(file.FileName);
                    //var fileName = Path.GetFileName(file.FileName);
                    String path = Path.Combine(Server.MapPath("~/Images/"), photoName + extension);
                    imagePath = "~/Images/" + photoName + extension;
                    file.SaveAs(path);                 
                }
            }

            return imagePath;
        }

        // POST: TabFotos/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Tipo,Codigo,item,titulo,descripcion,foto")] TabFotos tabFotos)
        {
            ViewBag.Observacion = "";


            if (ModelState.IsValid)
            {
                var datos=tabFotosRepository.GetOne(x=>x.Codigo.Equals(tabFotos.Codigo) 
                && x.item==tabFotos.item 
                && x.Tipo.Equals(tabFotos.Tipo)
                ,null);

                if (datos == null)
                {
                    tabFotosRepository.Insert(tabFotos);

                    var pathFoto = subirFoto(tabFotos.Codigo, tabFotos.item + "");
                    if (pathFoto.Trim().Length > 0)
                    {                        
                        tabFotos.foto = pathFoto;                       
                    }else
                    {
                        tabFotos.foto = " ";
                    }

                    tabFotosRepository.Update(tabFotos);

                    return RedirectToAction( "Edit", "Productos", new { id = tabFotos.Codigo.Trim() });
                }
                else
                {
                    ViewBag.Observacion = "La foto ya existe en el registro del producto";
                }

            }

            ViewBag.Codigo = new SelectList(new ProductoRepository().GetList(null, null), "CodPro", "CodPro", tabFotos.Codigo);
            return View(tabFotos);
        }

        // GET: TabFotos/Edit/5
        public ActionResult Edit(string tipo, string codigo,int item)
        {
            @ViewBag.resultado = TempData["resultado"];
            TempData["resultado"] = null;

            if (tipo == null || codigo==null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TabFotos tabFotos = tabFotosRepository.GetOne(x=>x.Tipo.Equals(tipo) 
            && x.Codigo.Equals(codigo) 
            && x.item==item,null);

            if (tabFotos == null)
            {
                return HttpNotFound();
            }
            ViewBag.Codigo = new SelectList(new ProductoRepository().GetList(null, null), 
                "CodPro", "CodLin", tabFotos.Codigo);
            return View(tabFotos);
        }

        // POST: TabFotos/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Tipo,Codigo,item,titulo,descripcion,foto")] TabFotos tabFotos)
        {
            var pathFoto = "";
            if (ModelState.IsValid)
            {
               
                TempData["resultado"] = "Grabacion satisfactoria";

                pathFoto = subirFoto(tabFotos.Codigo, tabFotos.item + "");
                if (pathFoto.Trim().Length > 0)
                {
                    tabFotos.foto = pathFoto;               
                }

                tabFotosRepository.Update(tabFotos);

            }

            return RedirectToAction("Edit", new { Tipo = tabFotos.Tipo.Trim(), Codigo = tabFotos.Codigo.Trim(), item = tabFotos.item });
        }

        // GET: DomClis/Delete/5
        public ActionResult Delete(string tipo, string codigo, int item)
        {
            var tabFotos = tabFotosRepository.GetOne(x => x.Tipo.Equals(tipo) &&
                     x.Codigo.Equals(codigo) && x.item==item, null);

            tabFotosRepository.Delete(tabFotos);

            return RedirectToAction("Edit", "Productos", new { id = tabFotos.Codigo.Trim() });
        }
        
    }
}

Aplication/Web/Views/Productos/Create.cshtml
@model DAL.Models.Producto


@{
    ViewBag.Title = "Nuevo Producto";
}

<div class="row">
    <div class="col-sm-12">
        <div class="card-box">
            <div class="card-head">
                <header>Nuevo Producto</header>
                <button id="panel-button"
                        class="mdl-button mdl-js-button mdl-button--icon pull-right hidden"
                        data-upgraded=",MaterialButton">
                    <i class="material-icons">more_vert</i>
                </button>
                <ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect"
                    data-mdl-for="panel-button">
                    <li class="mdl-menu__item"><i class="material-icons">assistant_photo</i>Action</li>
                    <li class="mdl-menu__item"><i class="material-icons">print</i>Another action</li>
                    <li class="mdl-menu__item"><i class="material-icons">favorite</i>Something else here</li>
                </ul>
            </div>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="card-body row">
                <div class="col-lg-6 p-t-20">
                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label txt-full-width">
                        @Html.EditorFor(model => model.NomPro, new { htmlAttributes = new { @class = "mdl-textfield__input" } })
                        @Html.LabelFor(model => model.NomPro, htmlAttributes: new { @class = "mdl-textfield__label" })
                        @Html.ValidationMessageFor(model => model.NomPro, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-lg-6 p-t-20">
                    @Html.LabelFor(model => model.CodLin, "CodLin", htmlAttributes: new { @class = "mdl-textfield__label col-md-2" })
                    <br />
                    @Html.DropDownList("CodLin", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CodLin, "", new { @class = "text-danger" })
                </div>
                <div class="col-lg-6 p-t-20">
                    @Html.LabelFor(model => model.CodSubLin, "CodSubLin", htmlAttributes: new { @class = "mdl-textfield__label col-md-2" })
                    <br />
                    @Html.DropDownList("CodSubLin", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CodSubLin, "", new { @class = "text-danger" })
                </div>
                <div class="col-lg-6 p-t-20">
                    @Html.LabelFor(model => model.estado, "Estado", htmlAttributes: new { @class = "mdl-textfield__label col-md-2" })
                    <br />
                    @Html.DropDownListFor(model => model.estado, new SelectList(
                    new List<Object>{
                    new { value = "001" , text = "Activo"  },
                    new { value = "002" , text = "Anulado" },
                    },
                    "value",
                    "text",
                    2), new { @class = "form-control" })
                    <br />
                </div>
                <div class="col-lg-6 p-t-20">
                    @Html.LabelFor(model => model.CodUniMed, "CodUniMed", htmlAttributes: new { @class = "mdl-textfield__label col-md-2" })
                    <br />
                    @Html.DropDownList("CodUniMed", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CodSubLin, "", new { @class = "text-danger" })
                </div>
                <div class="col-lg-6 p-t-20">
                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label txt-full-width">
                        @Html.EditorFor(model => model.precio, new { htmlAttributes = new { @class = "mdl-textfield__input" } })
                        @Html.LabelFor(model => model.precio, htmlAttributes: new { @class = "mdl-textfield__label" })
                        @Html.ValidationMessageFor(model => model.precio, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-lg-6 p-t-20">
                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label txt-full-width">
                        @Html.EditorFor(model => model.afectoigv, new { htmlAttributes = new { @class = "mdl-textfield__input" } })
                        @Html.LabelFor(model => model.afectoigv, htmlAttributes: new { @class = "mdl-textfield__label" })
                        @Html.ValidationMessageFor(model => model.afectoigv, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-lg-6 p-t-20">
                    @Html.LabelFor(model => model.TipPro, "Tipo Prod", htmlAttributes: new { @class = "mdl-textfield__label col-md-2" })
                    <br />
                    @Html.DropDownListFor(model => model.TipPro, new SelectList(
                    new List<Object>{
                    new { value = "VE" , text = "Venta"  },
                    new { value = "BO" , text = "Bonificacion" },
                    new { value = "IN" , text = "Insumo" },
                    },
                    "value",
                    "text",
                    2), new { @class = "form-control" })
                    <br />
                </div>

                <div class="row col-12">
                    <div class="col-6 text-left">
                        @Html.ActionLink("reply_all", "Index", null, new { @class = "material-icons", data_toggle = "tooltip", data_placement = "top", title = "Volver", @style = "color:black" })
                    </div>

                    <div class="col-6 text-right">
                        <button type="submit" class="material-icons" data-toggle="tooltip" data-placement="top" title="Grabar">save</button>
                    </div>
                </div>

            </div>
            }

        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Aplication/Web/Views/Productos/Delete.cshtml
@model DAL.Models.Producto

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Producto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LineaProducto.DesLin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LineaProducto.DesLin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SubLineaProducto.CodLin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SubLineaProducto.CodLin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UnidadMedida.DesUniMed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UnidadMedida.DesUniMed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NomPro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NomPro)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.estado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.precio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.precio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.afectoigv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.afectoigv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipPro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipPro)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Aplication/Web/Views/Productos/Edit.cshtml
@model DAL.Models.Producto

@{
    ViewBag.Title = "Editar Producto";
}

<div class="row">
    <div class="col-sm-12">
        <div class="card-box">
            <div class="card-head">
                <header>Editar Producto</header>
                <button id="panel-button"
                        class="mdl-button mdl-js-button mdl-button--icon pull-right hidden"
                        data-upgraded=",MaterialButton">
                    <i class="material-icons">more_vert</i>
                </button>
                <ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect"
                    data-mdl-for="panel-button">
                    <li class="mdl-menu__item"><i class="material-icons">assistant_photo</i>Action</li>
                    <li class="mdl-menu__item"><i class="material-icons">print</i>Another action</li>
                    <li class="mdl-menu__item"><i class="material-icons">favorite</i>Something else here</li>
                </ul>
            </div>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
   

            <div class="card-body row">
                <div class="col-lg-6 p-t-20">
                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label txt-full-width disabled">
                        @Html.EditorFor(model => model.CodPro, new { htmlAttributes = new { @class = "mdl-textfield__input", @readonly = "readonly", @style = "background: #f7f7f7;" } })
                        @Html.LabelFor(model => model.CodPro, htmlAttributes: new { @class = "mdl-textfield__label" })
                        @Html.ValidationMessageFor(model => model.CodPro, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-lg-6 p-t-20">
                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label txt-full-width">
                        @Html.EditorFor(model => model.NomPro, new { htmlAttributes = new { @class = "mdl-textfield__input" } })
                        @Html.LabelFor(model => model.NomPro, htmlAttributes: new { @class = "mdl-textfield__label" })
                        @Html.ValidationMessageFor(model => model.NomPro, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-lg-6 p-t-20">
                    @Html.LabelFor(model => model.CodLin, "CodLin", htmlAttributes: new { @class = "mdl-textfield__label col-md-2" })
                    <br />
                    @Html.DropDownList("CodLin", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CodLin, "", new { @class = "text-danger" })
                </div>
                <div class="col-lg-6 p-t-20">
                    @Html.LabelFor(model => model.CodSubLin, "CodSubLin", htmlAttributes: new { @class = "mdl-textfield__label col-md-2" })
                    <br />
                    @Html.DropDownList("CodSubLin", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CodSubLin, "", new { @class = "text-danger" })
                </div>
                <div class="col-lg-6 p-t-20">
                    @Html.LabelFor(model => model.estado, "Estado", htmlAttributes: new { @class = "mdl-textfield__label col-md-2" })
                    <br />
                    @Html.DropDownListFor(model => model.estado, new SelectList(
                    new List<Object>{
                    new { value = "001" , text = "Activo"  },
                    new { value = "002" , text = "Anulado" },
                    },
                    "value",
                    "text",
                    2), new { @class = "form-control" })
                    <br />
                </div>
                <div class="col-lg-6 p-t-20">
                    @Html.LabelFor(model => model.CodUniMed, "CodUniMed", htmlAttributes: new { @class = "mdl-textfield__label col-md-2" })
                    <br />
                    @Html.DropDownList("CodUniMed", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CodSubLin, "", new { @class = "text-danger" })
                </div>
                <div class="col-lg-6 p-t-20">
                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label txt-full-width">
                        @Html.EditorFor(model => model.precio, new { htmlAttributes = new { @class = "mdl-textfield__input" } })
                        @Html.LabelFor(model => model.precio, htmlAttributes: new { @class = "mdl-textfield__label" })
                        @Html.ValidationMessageFor(model => model.precio, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-lg-6 p-t-20">
                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label txt-full-width">
                        @Html.EditorFor(model => model.afectoigv, new { htmlAttributes = new { @class = "mdl-textfield__input" } })
                        @Html.LabelFor(model => model.afectoigv, htmlAttributes: new { @class = "mdl-textfield__label" })
                        @Html.ValidationMessageFor(model => model.afectoigv, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-lg-6 p-t-20">
                    @Html.LabelFor(model => model.TipPro, "Tipo Prod", htmlAttributes: new { @class = "mdl-textfield__label col-md-2" })
                    <br />
                    @Html.DropDownListFor(model => model.TipPro, new SelectList(
                    new List<Object>{
                    new { value = "VE" , text = "Venta"  },
                    new { value = "BO" , text = "Bonificacion" },
                    new { value = "IN" , text = "Insumo" },
                    },
                    "value",
                    "text",
                    2), new { @class = "form-control" })
                    <br />
                </div>


                <div class="row col-12">
                    <div class="col-6 text-left">
                        @Html.ActionLink("reply_all", "Index", null, new { @class = "material-icons", data_toggle = "tooltip", data_placement = "top", title = "Volver", @style = "color:black" })
                    </div>

                    <div class="col-6 text-right">
                        <button type="submit" class="material-icons" data-toggle="tooltip" data-placement="top" title="Grabar">save</button>
                    </div>
                </div>


            </div>
                }
            </div>
    </div>
</div>



<div class="row">
    <div class=" pull-left col-12">
        <div class="page-title">Fotos del producto</div>
    </div>
    <div class="pull-left col-12">
        @Html.ActionLink("Crear Nueva Foto", "Create", "TabFotos", new { CodPro = Model.CodPro }, new { @class = "btn btn-success btn-rounded waves-effect waves-light m-t-20" })

    </div>
</div>

<br />


<div class="row">
    @foreach (var item in Model.TabFotos)
    {
        <div class="col-lg-3 col-md-6 col-12 col-sm-6">
            <div class="blogThumb">
                <div class="thumb-center"><img class="img-responsive" height="200" width="300" alt=" " src="@Url.Content(item.foto)"></div>
                <div class="white-box">
                    <p>
                        Item:
                        @Html.DisplayFor(modelItem => item.item)
                        <br />
                        Titulo:
                        @Html.DisplayFor(modelItem => item.titulo)
                        <br />
                        Descripcion:
                        @Html.DisplayFor(modelItem => item.descripcion)
                    
                    </p>
                    @Html.ActionLink("create", "Edit", "TabFotos", new { Tipo = item.Tipo.Trim(), Codigo = item.Codigo.Trim(), item = item.item }, new { @class = "material-icons", data_toggle = "tooltip", data_placement = "top", title = "Volver", @style = "color:black;margin-right:20px" })
                    @Html.ActionLink("delete", "Delete", "TabFotos", new { Tipo = item.Tipo.Trim(), Codigo = item.Codigo.Trim(), item = item.item }, new { @class = "material-icons", data_toggle = "tooltip", data_placement = "top", title = "Eliminar", @style = "color:black" })
                </div>
            </div>
        </div>
    }
</div>





@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}